stages:
  - build
  - release

image: docker:20.10.16
services:
    - docker:20.10.16-dind

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-${CI_PIPELINE_ID}  -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA} -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG} .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-${CI_PIPELINE_ID}  -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA} -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}

release-image:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-${CI_PIPELINE_ID}
    - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-${CI_PIPELINE_ID} $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
